version: "3.9"

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: boilerplate
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '5432:5432'
    volumes:
      - boilerplate-postgres:/var/lib/postgresql/data

  boilerplate:
    build:
      context: .
    volumes:
      - ./boilerplate:/opt/app
    links:
      - postgres
    ports:
      - '8010:8010'
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - boilerplate
    ports:
      - '3000:3000'

volumes:
  boilerplate-postgres:
